//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hotel_System.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Hotel_System.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _10724993 {
            get {
                object obj = ResourceManager.GetObject("10724993", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _1205761_removebg_preview_300x300 {
            get {
                object obj = ResourceManager.GetObject("1205761-removebg-preview-300x300", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _124056 {
            get {
                object obj = ResourceManager.GetObject("124056", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _1649292 {
            get {
                object obj = ResourceManager.GetObject("1649292", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _2721227 {
            get {
                object obj = ResourceManager.GetObject("2721227", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _3652267 {
            get {
                object obj = ResourceManager.GetObject("3652267", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _36522671 {
            get {
                object obj = ResourceManager.GetObject("36522671", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _3917762 {
            get {
                object obj = ResourceManager.GetObject("3917762", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _4387725_2341457_removebg_preview {
            get {
                object obj = ResourceManager.GetObject("4387725_2341457-removebg-preview", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap d2b01052124d637b98d00d0e595b8965 {
            get {
                object obj = ResourceManager.GetObject("d2b01052124d637b98d00d0e595b8965", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap d2b01052124d637b98d00d0e595b89651 {
            get {
                object obj = ResourceManager.GetObject("d2b01052124d637b98d00d0e595b89651", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap file_archive_icon_193973 {
            get {
                object obj = ResourceManager.GetObject("file_archive_icon_193973", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap home_icon {
            get {
                object obj = ResourceManager.GetObject("home-icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap hotel_logo_design_service11 {
            get {
                object obj = ResourceManager.GetObject("hotel-logo-design-service11", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap IMG_20240502_WA0006 {
            get {
                object obj = ResourceManager.GetObject("IMG-20240502-WA0006", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap IMG_20240502_WA0008 {
            get {
                object obj = ResourceManager.GetObject("IMG-20240502-WA0008", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap IMG_20240502_WA0009 {
            get {
                object obj = ResourceManager.GetObject("IMG-20240502-WA0009", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap IMG_20240502_WA0012 {
            get {
                object obj = ResourceManager.GetObject("IMG-20240502-WA0012", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap IMG_20240502_WA0017 {
            get {
                object obj = ResourceManager.GetObject("IMG-20240502-WA0017", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap louer_une_chambre_d_hotel_pour_l_icone_rvb_a_court_terme_reservation_d_hebergement_installation_de_logement_passer_la_nuit_a_l_auberge_equipements_de_voyage_2bdcnca {
            get {
                object obj = ResourceManager.GetObject("louer-une-chambre-d-hotel-pour-l-icone-rvb-a-court-terme-reservation-d-hebergemen" +
                        "t-installation-de-logement-passer-la-nuit-a-l-auberge-equipements-de-voyage-2bdc" +
                        "nca", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap louer_une_chambre_d_hotel_pour_l_icone_rvb_a_court_terme_reservation_d_hebergement_installation_de_logement_passer_la_nuit_a_l_auberge_equipements_de_voyage_2bdcnca1 {
            get {
                object obj = ResourceManager.GetObject("louer-une-chambre-d-hotel-pour-l-icone-rvb-a-court-terme-reservation-d-hebergemen" +
                        "t-installation-de-logement-passer-la-nuit-a-l-auberge-equipements-de-voyage-2bdc" +
                        "nca1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap louer_une_chambre_d_hotel_pour_l_icone_rvb_a_court_terme_reservation_d_hebergement_installation_de_logement_passer_la_nuit_a_l_auberge_equipements_de_voyage_2bdcnca2 {
            get {
                object obj = ResourceManager.GetObject("louer-une-chambre-d-hotel-pour-l-icone-rvb-a-court-terme-reservation-d-hebergemen" +
                        "t-installation-de-logement-passer-la-nuit-a-l-auberge-equipements-de-voyage-2bdc" +
                        "nca2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap mark_task_check_file_document_list_checklist_report_icon_231916 {
            get {
                object obj = ResourceManager.GetObject("mark_task_check_file_document_list_checklist_report_icon_231916", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap png_clipart_computer_icons_exit_icon_miscellaneous_angle {
            get {
                object obj = ResourceManager.GetObject("png-clipart-computer-icons-exit-icon-miscellaneous-angle", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap png_clipart_computer_icons_exit_icon_miscellaneous_angle1 {
            get {
                object obj = ResourceManager.GetObject("png-clipart-computer-icons-exit-icon-miscellaneous-angle1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap png_clipart_computer_icons_exit_icon_miscellaneous_angle2 {
            get {
                object obj = ResourceManager.GetObject("png-clipart-computer-icons-exit-icon-miscellaneous-angle2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap png_clipart_exit_sign_button_emergency_exit_sticker_button_building_push_thumbnail {
            get {
                object obj = ResourceManager.GetObject("png-clipart-exit-sign-button-emergency-exit-sticker-button-building-push-thumbnai" +
                        "l", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap png_clipart_favicon_icon_add_sign_s_mobile_phone_symbol {
            get {
                object obj = ResourceManager.GetObject("png-clipart-favicon-icon-add-sign-s-mobile-phone-symbol", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap png_clipart_favicon_icon_add_sign_s_mobile_phone_symbol1 {
            get {
                object obj = ResourceManager.GetObject("png-clipart-favicon-icon-add-sign-s-mobile-phone-symbol1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap png_transparent_back_button_arrow_icon_the_direction_of_the {
            get {
                object obj = ResourceManager.GetObject("png-transparent-back-button-arrow-icon-the-direction-of-the", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap pngtree_orange_and_gray_flat_home_button_with_round_shape_vector_png_image_19437864 {
            get {
                object obj = ResourceManager.GetObject("pngtree-orange-and-gray-flat-home-button-with-round-shape-vector-png-image_194378" +
                        "64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap pngtree_orange_and_gray_flat_home_button_with_round_shape_vector_png_image_194378641 {
            get {
                object obj = ResourceManager.GetObject("pngtree-orange-and-gray-flat-home-button-with-round-shape-vector-png-image_194378" +
                        "641", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap power_icon {
            get {
                object obj = ResourceManager.GetObject("power-icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap restaurant_chef_logo_icon_symbol_cooking_imagination_hat_for_company_2JN8960 {
            get {
                object obj = ResourceManager.GetObject("restaurant-chef-logo-icon-symbol-cooking-imagination-hat-for-company-2JN8960", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Screenshot_٢٠٢٤٠٥١٨_١٨٤٢٤٦ {
            get {
                object obj = ResourceManager.GetObject("Screenshot_٢٠٢٤٠٥١٨-١٨٤٢٤٦", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Screenshot_٢٠٢٤٠٥١٨_١٨٤٣٠١ {
            get {
                object obj = ResourceManager.GetObject("Screenshot_٢٠٢٤٠٥١٨-١٨٤٣٠١", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Screenshot_٢٠٢٤٠٥١٨_١٨٤٣٠١_2 {
            get {
                object obj = ResourceManager.GetObject("Screenshot_٢٠٢٤٠٥١٨-١٨٤٣٠١~2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap settings_icon {
            get {
                object obj = ResourceManager.GetObject("settings-icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
